from elasticsearch_dsl import Search
from examples.beaconing.generator import Generator
import numpy as np
import utils.read_scripted_metric as read_scripted_metric

class Test:
    def __init__(self,
                 user_name: str = '',
                 password: str = ''):
        self.generator = Generator(user_name, password)

    def es_client(self):
        return self.generator.es_client()

    def setup_generated(self):
        '''
        Generate some data used for testing.

        This isn't run as part setup because it relatively heavyweight.
        '''
        self.generator.generate_and_index_demo_data()

    def test_generated(self):
        '''
        Test the frequent item set scipted metric aggregation on the data set
        generated by setup_generated vs a python reference implementation.
        '''

        # TODO
